### ISSUE TITLE
Embedly API returns Bad Request for any URL

### ISSUE THREAD

**Issue by k-rudy** [embedly/embedly-ruby#39]
Hey guys,

Seems like starting from yesterday we are seeing `Bad Request` on any attempt to process any url.

The way we use the gem hasn't changed:

```
class EmbedlyExtractor
  def initialize
    @api = Embedly::API.new key: ENV['EMBEDLY_API_KEY'],
                            timeout: CourseUrl::EXTERNAL_SERVICES_TIMEOUT_IN_SECONDS,
                            user_agent: 'Mozilla/5.0 (compatible; exceedlms/1.0; admin@intellum.com)'
  end

  def extract(url)
    @api.extract(url: url).first
  end
end
```

The exception is:

```
Embedly::BadResponseException: Bad Response : #<Typhoeus::Response:0x00007f46c2b608e0
  
```

Does anybody else have this issue or know what's going on?

Thanks in advance.

**Comment by endorfin** [comment]
In our case, the error has appeared in the logs since 02.06 @ 18:11

The current hostname is http://api.embed.ly. This will be automatically redirected to HTTPS => https://api.embed.ly which causes the corresponding error.

I have already created a pull request #38 which uses the URL https://api.embedly.com from the documentation.

Hotfix for all until the error is fixed:

```
embedly_api = Embedly::API.new(
  key: YOUR_API_KEY,
  hostname: 'https://api.embedly.com'
)
```

**Comment by k-rudy** [comment]
The issue has been fixed on Embedly side. Closing.
